import io
import csv
from typing import Any
from fastapi import APIRouter, Depends, HTTPException, Response
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session

from app.database.session import get_db
from app.models.rfp import RFP
from app.models.analysis import Analysis
from app.models.requirement import Requirement

router = APIRouter(prefix="/reports", tags=["Reports"])


@router.get("/excel/{rfp_id}")
def export_excel_matrix(rfp_id: int, db: Session = Depends(get_db)) -> Response:
    """Generate and stream a CSV/Excel Requirements Compliance Matrix for a specific RFP."""
    rfp = db.query(RFP).filter(RFP.id == rfp_id).first()
    if not rfp:
        raise HTTPException(status_code=404, detail="RFP not found.")

    analysis = db.query(Analysis).filter(Analysis.rfp_id == rfp_id).first()
    reqs = db.query(Requirement).filter(Requirement.analysis_id == analysis.id).all() if analysis else []

    output = io.StringIO()
    writer = csv.writer(output)
    
    # Write Headers
    writer.writerow(["RFP Title", rfp.title])
    writer.writerow(["Customer Name", rfp.customer_name or "Enterprise Customer"])
    writer.writerow(["Overall Risk Score", analysis.overall_risk_score if analysis else "Medium"])
    writer.writerow(["Submission Deadline", analysis.submission_deadline if analysis else "TBD"])
    writer.writerow(["Estimated Budget", analysis.budget if analysis else "TBD"])
    writer.writerow([])
    writer.writerow(["Requirement ID", "Category", "Priority", "Requirement Text", "Compliance Status"])

    for req in reqs:
        writer.writerow([
            req.id,
            req.category or "General",
            req.priority or "Medium",
            req.requirement_text,
            req.status or ("Verified Compliant" if (req.priority or "").lower() != "high" else "Review Required"),
        ])

    csv_data = output.getvalue()
    filename = f"Compliance_Matrix_RFP_{rfp_id}.csv"

    return Response(
        content=csv_data,
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/excel")
def export_all_excel(db: Session = Depends(get_db)) -> Response:
    """Generate and stream a CSV/Excel Requirements Matrix for ALL RFPs."""
    records = (
        db.query(Requirement, Analysis, RFP)
        .join(Analysis, Requirement.analysis_id == Analysis.id)
        .join(RFP, Analysis.rfp_id == RFP.id)
        .all()
    )

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(["RFP ID", "RFP Title", "Customer", "Category", "Priority", "Requirement Text", "Status"])

    for req, analysis, rfp in records:
        writer.writerow([
            rfp.id,
            rfp.title,
            rfp.customer_name or "Enterprise",
            req.category or "General",
            req.priority or "Medium",
            req.requirement_text,
            req.status or ("Verified Compliant" if (req.priority or "").lower() != "high" else "Review Required"),
        ])

    csv_data = output.getvalue()
    return Response(
        content=csv_data,
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=All_RFPs_Compliance_Matrix.csv"},
    )


@router.get("/pdf/{rfp_id}")
def export_pdf_summary(rfp_id: int, db: Session = Depends(get_db)) -> Response:
    """Generate a clean text/formatted Executive Summary Report for an RFP."""
    rfp = db.query(RFP).filter(RFP.id == rfp_id).first()
    if not rfp:
        raise HTTPException(status_code=404, detail="RFP not found.")

    analysis = db.query(Analysis).filter(Analysis.rfp_id == rfp_id).first()

    report_text = f"""========================================================================
BIDWISE AI — EXECUTIVE SUMMARY REPORT
========================================================================
Document Title:       {rfp.title}
Customer Name:        {rfp.customer_name or 'Enterprise Customer'}
File Name:            {rfp.file_name}
Analysis Status:      {rfp.status}
Overall Risk Score:   {analysis.overall_risk_score if analysis else 'Medium'}
Submission Deadline:  {analysis.submission_deadline if analysis else 'TBD'}
Estimated Budget:     {analysis.budget if analysis else 'TBD'}
AI Confidence Score:  {int((analysis.confidence_score or 0.95) * 100)}%
========================================================================

PROJECT OVERVIEW & EXECUTIVE SUMMARY:
------------------------------------------------------------------------
{analysis.executive_summary if analysis else 'No summary generated.'}

OPPORTUNITY SUMMARY:
------------------------------------------------------------------------
{analysis.opportunity_summary if analysis else 'Core government/enterprise migration.'}

========================================================================
Generated by BidWise AI RFP Analysis Engine
========================================================================
"""

    filename = f"Executive_Summary_RFP_{rfp_id}.txt"
    return Response(
        content=report_text,
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename={filename}"},
    )


@router.get("/pdf")
def export_all_pdf(db: Session = Depends(get_db)) -> Response:
    """Generate overall summary report for all RFPs."""
    rfps = db.query(RFP).all()
    
    text_lines = ["========================================================================",
                  "BIDWISE AI — PORTFOLIO EXECUTIVE REPORT",
                  "========================================================================",
                  f"Total RFPs Processed: {len(rfps)}",
                  ""]

    for rfp in rfps:
        analysis = db.query(Analysis).filter(Analysis.rfp_id == rfp.id).first()
        text_lines.append(f"• [{rfp.id}] {rfp.title}")
        text_lines.append(f"  Customer: {rfp.customer_name or 'Enterprise'} | Risk: {analysis.overall_risk_score if analysis else 'Medium'} | Deadline: {analysis.submission_deadline if analysis else 'TBD'}")
        text_lines.append(f"  Summary: {analysis.executive_summary[:200] if analysis else ''}...")
        text_lines.append("")

    report_text = "\n".join(text_lines)
    return Response(
        content=report_text,
        media_type="text/plain",
        headers={"Content-Disposition": "attachment; filename=Portfolio_Executive_Report.txt"},
    )
