"""add extracted text fields

Revision ID: dbd5527b979c
Revises: 7087ffc2aaed
Create Date: 2026-07-06 21:04:27.527284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbd5527b979c'
down_revision: Union[str, Sequence[str], None] = '7087ffc2aaed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rfps', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('rfps', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rfps', 'error_message')
    op.drop_column('rfps', 'extracted_text')
    # ### end Alembic commands ###
